In [9]:
# ===============================
# Import libraries
# ===============================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


# ===============================
# Loading
# ===============================
df = pd.read_csv("iris.csv")
print("Columns:", df.columns.tolist())


# ===============================
# Separate features and target
# ===============================
X = df.drop(["Id", "Species"], axis=1)
y = df["Species"]


# ===============================
# Encode target variable
# ===============================
le = LabelEncoder()
y = le.fit_transform(y)


# ===============================
# Train-test split
# ===============================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


# ===============================
# Feature scaling
# ===============================
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


# ===============================
# Create and train KNN model
# ===============================
knn = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
knn.fit(X_train, y_train)


# ===============================
# Make predictions
# ===============================
y_pred = knn.predict(X_test)


# ===============================
# Model evaluation
# ===============================
print("\nAccuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


# ===============================
# Predict for a new flower (example)
# ===============================
new_sample = pd.DataFrame(
    [[5.1, 3.5, 1.4, 0.2]],
    columns=X.columns
)

new_sample_scaled = scaler.transform(new_sample)

prediction = knn.predict(new_sample_scaled)
print("\nPredicted Species:", le.inverse_transform(prediction))


Columns: ['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species']

Accuracy: 1.0

Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30


Predicted Species: ['Iris-setosa']
